# SPDX-FileCopyrightText: 2024 antlers <antlers@illucid.net>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "COPYING-DOCS"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "Copyright (c) 2013 Creative Commons"

[[annotations]]
path = [
  "STLs/*",
  "STEPs/*"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "Copyright (c) 2024 antlers <antlers@illucid.net>"
